#pragma once

// Version info
#define DEF_NOXCOIN_VERSION_TAG "test"       // or "v0.0.4" etc.
#define DEF_NOXCOIN_VERSION "0.0.4.0"
#define DEF_NOXCOIN_RELEASE_NAME "MinorPool"
#define DEF_NOXCOIN_VERSION_FULL DEF_NOXCOIN_VERSION "-" DEF_NOXCOIN_VERSION_TAG
#define DEF_NOXCOIN_VERSION_IS_RELEASE true  // set to true or false

// Constants
const char* const NOXCOIN_VERSION_TAG = DEF_NOXCOIN_VERSION_TAG;
const char* const NOXCOIN_VERSION = DEF_NOXCOIN_VERSION;
const char* const NOXCOIN_RELEASE_NAME = DEF_NOXCOIN_RELEASE_NAME;
const char* const NOXCOIN_VERSION_FULL = DEF_NOXCOIN_VERSION_FULL;
const bool NOXCOIN_VERSION_IS_RELEASE = DEF_NOXCOIN_VERSION_IS_RELEASE;
